#!/bin/bash

echo "🔥 Firebase Console - Disable App Check/reCAPTCHA"
echo "=================================================="
echo ""
echo "Follow these steps to fix the reCAPTCHA error:"
echo ""
echo "1. Open Firebase Console:"
echo "   https://console.firebase.google.com/project/ivmg-eebef/authentication/settings"
echo ""
echo "2. Click on 'Authentication' in the left sidebar"
echo ""
echo "3. Click on 'Settings' tab"
echo ""
echo "4. Scroll down to 'Advanced' section"
echo ""
echo "5. Find 'App verification' or 'Enable App Verification'"
echo ""
echo "6. DISABLE the following:"
echo "   ☐ Phone sign-in recaptcha verifier (Disable)"
echo "   ☐ Email enumeration protection (Disable)"
echo ""
echo "7. Click 'Save'"
echo ""
echo "=================================================="
echo ""
echo "Alternative: Use Cloud Functions to create users"
echo "OR manually create first admin in Firebase Console"
echo ""
