// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLOUIbW9iy76rGLFPV2ytFjHknNscbHx0',
    appId: '1:860436601508:web:cadb7dcff094c3e5f0a431',
    messagingSenderId: '860436601508',
    projectId: 'ivmg-eebef',
    authDomain: 'ivmg-eebef.firebaseapp.com',
    storageBucket: 'ivmg-eebef.firebasestorage.app',
    measurementId: 'G-6SN6H4ZXTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL1bgIl8qlWj-m3BFBSpRz2UUkZqQT3jM',
    appId: '1:860436601508:android:af5cabdf3120f1abf0a431',
    messagingSenderId: '860436601508',
    projectId: 'ivmg-eebef',
    storageBucket: 'ivmg-eebef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBASskXJSqGZWhtN2ZFNKCHz-cRGE-CS8A',
    appId: '1:860436601508:ios:7c1847362606cdd5f0a431',
    messagingSenderId: '860436601508',
    projectId: 'ivmg-eebef',
    storageBucket: 'ivmg-eebef.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBASskXJSqGZWhtN2ZFNKCHz-cRGE-CS8A',
    appId: '1:860436601508:ios:7c1847362606cdd5f0a431',
    messagingSenderId: '860436601508',
    projectId: 'ivmg-eebef',
    storageBucket: 'ivmg-eebef.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLOUIbW9iy76rGLFPV2ytFjHknNscbHx0',
    appId: '1:860436601508:web:afeffd2c48f94695f0a431',
    messagingSenderId: '860436601508',
    projectId: 'ivmg-eebef',
    authDomain: 'ivmg-eebef.firebaseapp.com',
    storageBucket: 'ivmg-eebef.firebasestorage.app',
    measurementId: 'G-96R1LT9QM7',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCLOUIbW9iy76rGLFPV2ytFjHknNscbHx0',
    appId: '1:860436601508:web:afeffd2c48f94695f0a431',
    messagingSenderId: '860436601508',
    projectId: 'ivmg-eebef',
    authDomain: 'ivmg-eebef.firebaseapp.com',
    storageBucket: 'ivmg-eebef.firebasestorage.app',
    measurementId: 'G-96R1LT9QM7',
  );
}
